import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import stylesUtils from '../styles/utilities.module.css'
import Header from '../components/Header';
import Window from '../components/Window';
import { Component } from 'react';

interface IProps {
}

interface IState {
  windows: number[];
}

export default class Home extends Component<IProps, IState> {

  constructor(props: IProps) {

    super(props);
    this.state = {
      windows: []
    }
    this.onNewChart = this.onNewChart.bind(this);
  }

  onNewChart(){
    var newState: number[];
    newState = this.state.windows.slice();
    newState.push(0);
    this.setState({windows : newState});
  }

  render() {
    return (
      <div className={stylesUtils.h100}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
          <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet" />
        </Head>
        <Header onNewChartClicked={this.onNewChart} onNewTapeClicked={this.onNewChart}/>

        <div className={styles.windowsContainer}>
          {
            this.state.windows.map((item) => (
              <Window />
            ))
          }
        </div>

      </div>
    )
  }
}
